### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GDBlackRed** [nekitdev/gd.platformer#4]
The Image shows it all
https://imgur.com/B4QGfdI

**Comment by NeKitDS** [comment]
Cause of this error is likely to be incompatibility in Windows 7(?) and Windows 10 (system that the executable was built on)

**Comment by GDBlackRed** [comment]
It only works for Windows 10? can you make one for win 7?

**Comment by Bavfalcon9** [comment]
Either run from source `py ./gdplatformer.py`, or try regenerating the executable on windows 7.

**Comment by NeKitDS** [comment]
It's interesting how the thing is incompatible, either way.

There are two solutions:
- Install Python and grab ``gd.platformer`` via ``py -3 -m pip install gd.platformer``, then ``py -m gdplatformer`` to run it;
- Download the source via ``git clone https://github.com/NeKitDS/gd.platformer``, or just download the ``.zip`` from GitHub, then navigate to the folder with ``gdplatformer.py``, install Python and ``PyInstaller``, then compile your ``.exe`` using command described in the README of this project.
